### PR TITLE
DOSGI-280 - Upgrade to Aries RSA 1.14.0

### PR DESCRIPTION
**Pull request by amichair**
I wonder if we should leave the range limited to the next minor version, or use something like [1.14.0,2.0.0) ?

### CODE REVIEW

**Comment by coheigea** [comment]
The patch causes test failures due to:
org.osgi.framework.BundleException: Unable to resolve org.apache.cxf.cxf-rt-rs-service-description-swagger [68](R 68.0): missing requirement [org.apache.cxf.cxf-rt-rs-service-description-swagger [68](R 68.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.cxf.jaxrs.ext)(version>=3.2.0)(!(version>=4.0.0))) [caused by: Unable to resolve org.apache.cxf.cxf-rt-frontend-jaxrs [46](R 46.0): missing requirement [org.apache.cxf.cxf-rt-frontend-jaxrs [46](R 46.0)] osgi.wiring.package; (&(osgi.wiring.package=javax.annotation)(version>=1.3.0)(!(version>=2.0.0)))] Unresolved requirements: [[org.apache.cxf.cxf-rt-rs-service-description-swagger [68](R 68.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.cxf.jaxrs.ext)(version>=3.2.0)(!(version>=4.0.0)))]

**Comment by amichair** [comment]
Strange, I built it on two different machines with no error...

**Comment by amichair** [comment]
If you have an idea how I can recreate this error, I'd be happy to investigate. Is some difference in the environment leaking into the test? Should I be running something other than mvn clean install?

btw, in the previous commit upgrading CXF from 3.2.5 to 3.2.8, the range was changed to [3.2.5,3.2.8), shouldn't that be [3.2.8, 3.3.0) or something like that?

**Comment by coheigea** [comment]
@amichair What I'm doing is "wget https://patch-diff.githubusercontent.com/raw/apache/cxf-dosgi/pull/5.patch; git am apply 5.patch; mvn clean install"

Yes, I'll update the range.

**Comment by amichair** [comment]
Rebased on your commit - do you still get an error?

'git am apply' doesn't work, 'git apply' does. In any case the result is identical to checking out the DOSGI-280 branch, and the build is successful. So we're running the same tests on the same code (assuming working directory is otherwise clean) - what else might be different?

**Comment by coheigea** [comment]
I tried cloning your fork + building the DOSGI-280 branch but I get the same errors. Using Java 1.8 if that makes any difference.

**Comment by amichair** [comment]
I'm on Oracle JDK 1.8.0_201, Maven 3.6.0, Linux. Also not sure how the error above relates to RSA...

**Comment by coheigea** [comment]
please rebase off master.

**Comment by amichair** [comment]
Rebased. Still unable to recreate the build error.

btw perhaps we can get Jenkins to run a build on every push and PR for verification?

**Comment by coheigea** [comment]
It's working now for me for some reason, I guess due to the CXF upgrade.

**Pull request merged**
